/**
 * Fingerprint every bundled level and write php/internal_hashes.php — the server-side
 * blocklist that keeps players from uploading a copy of an official level as their own.
 *
 *   npx tsx src/dev/userlevel-hashes.ts
 *
 * Run it again whenever levels/ changes (new official levels), then re-deploy the
 * generated file. It also warns if two bundled levels share a fingerprint (a re-skin
 * slipping into the corpus).
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { LevelJson } from '../engine/index.ts'
import { levelHash } from '../game/levelHash.ts'

const dir = resolve(process.cwd(), 'levels')
const out = resolve(process.cwd(), 'php', 'internal_hashes.php')
const files = readdirSync(dir).filter((f) => f.endsWith('.json'))

const byHash = new Map<string, string>()
for (const file of files) {
  const json = JSON.parse(readFileSync(resolve(dir, file), 'utf8')) as LevelJson
  const hash = await levelHash(json)
  const twin = byHash.get(hash)
  if (twin) console.warn(`⚠ ${file} hat denselben Fingerprint wie ${twin}`)
  byHash.set(hash, file)
}

const lines = [...byHash.keys()].map((h) => `    '${h}' => true,`)
writeFileSync(
  out,
  `<?php\n\n` +
    `declare(strict_types=1);\n\n` +
    `// GENERATED by \`npx tsx src/dev/userlevel-hashes.ts\` — do not edit.\n` +
    `// Fingerprints of all ${byHash.size} bundled levels; uploads matching one are rejected.\n` +
    `return [\n${lines.join('\n')}\n];\n`,
)
console.log(`${byHash.size} Fingerprints → ${out}`)
